version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'LAVA' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: address_tags
      - name: dim_dates

  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'LAVA' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: number_sequence
      
  - name: bronze_streamline
    database: streamline
    schema: |
      "{{ 'LAVA' if target.database == 'LAVA' else 'LAVA_DEV' }}"
    tables:
      - name: blocks
      - name: tx_search
      - name: txcount
      - name: blockchain
      - name: testnet_blocks
      - name: testnet_tx_search
      - name: testnet_txcount
      - name: testnet_blockchain